Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "./program.zip/__main__.py", line 15, in <module>
TypeError: unsupported operand type(s) for -: 'int' and 'list'
